### ISSUE TITLE
Not able to override the severity of NotEmptyOrUnknown

### ISSUE THREAD

**Issue by LauraXiulan** [Qowaiv/qowaiv-validation#11]
When adding .withSeverity(Severity.Warning) to the .NotEmptyOrUnknown rule the severity is still Error.

**Comment by Corniel** [comment]
I can reproduce this.

Becuase `.NotEmptyOrUnknown()` is a combined validation of two, only the serverity of the unknown validation is overridden. That is a bug to me.
